# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_new_product.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from functions_anp import *


class Ui_window_anp(object):

    def clear_data(self):
        print('clear')
        f_clear_data(self)

    def add_product(self):
        print('add')
        f_add_product(self)

    def new_product(self):
        print('new')
        f_new_product(self)

    def edit_product(self):
        print('edit')
        f_edit_product(self)

    def find_product(self):
        print('find')
        f_find_product(self)

    def delete_product(self):
        print('del')
        f_delete_product(self)


    def setupUi(self, window_anp):
        window_anp.setObjectName("window_anp")
        window_anp.resize(971, 454)
        font = QtGui.QFont()
        font.setPointSize(9)
        window_anp.setFont(font)
        self.label = QtWidgets.QLabel(window_anp)
        self.label.setGeometry(QtCore.QRect(0, 20, 971, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(window_anp)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 90, 531, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(24)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 2, 1, 1)
        self.product_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_name.sizePolicy().hasHeightForWidth())
        self.product_name.setSizePolicy(sizePolicy)
        self.product_name.setSizeIncrement(QtCore.QSize(0, 0))
        self.product_name.setBaseSize(QtCore.QSize(0, 100))
        self.product_name.setObjectName("product_name")
        self.gridLayout.addWidget(self.product_name, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.cgst = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cgst.sizePolicy().hasHeightForWidth())
        self.cgst.setSizePolicy(sizePolicy)
        self.cgst.setSizeIncrement(QtCore.QSize(0, 0))
        self.cgst.setBaseSize(QtCore.QSize(0, 100))
        self.cgst.setPlaceholderText("")
        self.cgst.setClearButtonEnabled(False)
        self.cgst.setObjectName("cgst")
        self.gridLayout.addWidget(self.cgst, 5, 1, 1, 1)
        self.hsn_code = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hsn_code.sizePolicy().hasHeightForWidth())
        self.hsn_code.setSizePolicy(sizePolicy)
        self.hsn_code.setSizeIncrement(QtCore.QSize(0, 0))
        self.hsn_code.setBaseSize(QtCore.QSize(0, 100))
        self.hsn_code.setObjectName("hsn_code")
        self.gridLayout.addWidget(self.hsn_code, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 1)
        self.uom = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uom.sizePolicy().hasHeightForWidth())
        self.uom.setSizePolicy(sizePolicy)
        self.uom.setSizeIncrement(QtCore.QSize(0, 0))
        self.uom.setBaseSize(QtCore.QSize(0, 100))
        self.uom.setObjectName("uom")
        self.gridLayout.addWidget(self.uom, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.sgst = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sgst.sizePolicy().hasHeightForWidth())
        self.sgst.setSizePolicy(sizePolicy)
        self.sgst.setSizeIncrement(QtCore.QSize(0, 10))
        self.sgst.setBaseSize(QtCore.QSize(0, 100))
        self.sgst.setObjectName("sgst")
        self.gridLayout.addWidget(self.sgst, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.product_id = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_id.sizePolicy().hasHeightForWidth())
        self.product_id.setSizePolicy(sizePolicy)
        self.product_id.setSizeIncrement(QtCore.QSize(0, 0))
        self.product_id.setBaseSize(QtCore.QSize(0, 100))
        self.product_id.setText("")
        self.product_id.setReadOnly(True)
        self.product_id.setObjectName("product_id")
        self.gridLayout.addWidget(self.product_id, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(window_anp)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(111, 370, 421, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add.sizePolicy().hasHeightForWidth())
        self.button_add.setSizePolicy(sizePolicy)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_clear = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clear.sizePolicy().hasHeightForWidth())
        self.button_clear.setSizePolicy(sizePolicy)
        self.button_clear.setObjectName("button_clear")
        self.horizontalLayout.addWidget(self.button_clear)
        self.button_new = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_new.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_new.sizePolicy().hasHeightForWidth())
        self.button_new.setSizePolicy(sizePolicy)
        self.button_new.setObjectName("button_new")
        self.horizontalLayout.addWidget(self.button_new)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(window_anp)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(630, 370, 295, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_find = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_find.sizePolicy().hasHeightForWidth())
        self.button_find.setSizePolicy(sizePolicy)
        self.button_find.setObjectName("button_find")
        self.horizontalLayout_2.addWidget(self.button_find)
        self.button_delete = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_delete.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_delete.sizePolicy().hasHeightForWidth())
        self.button_delete.setSizePolicy(sizePolicy)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout_2.addWidget(self.button_delete)
        self.button_edit = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_edit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_edit.sizePolicy().hasHeightForWidth())
        self.button_edit.setSizePolicy(sizePolicy)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout_2.addWidget(self.button_edit)
        self.line = QtWidgets.QFrame(window_anp)
        self.line.setGeometry(QtCore.QRect(306, 410, 10, 3))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(window_anp)
        self.line_2.setGeometry(QtCore.QRect(450, 400, 10, 3))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.listOfProducts = QtWidgets.QListWidget(window_anp)
        self.listOfProducts.setGeometry(QtCore.QRect(640, 90, 256, 241))
        self.listOfProducts.setObjectName("listOfProducts")

        self.retranslateUi(window_anp)
        QtCore.QMetaObject.connectSlotsByName(window_anp)
        window_anp.setTabOrder(self.product_id, self.product_name)
        window_anp.setTabOrder(self.product_name, self.uom)
        window_anp.setTabOrder(self.uom, self.comboBox)
        window_anp.setTabOrder(self.comboBox, self.hsn_code)
        window_anp.setTabOrder(self.hsn_code, self.cgst)
        window_anp.setTabOrder(self.cgst, self.sgst)
        window_anp.setTabOrder(self.sgst, self.button_add)
        window_anp.setTabOrder(self.button_add, self.button_clear)
        window_anp.setTabOrder(self.button_clear, self.button_find)
        window_anp.setTabOrder(self.button_find, self.button_edit)

    def retranslateUi(self, window_anp):

        readyProducts(self)
        self.button_clear.clicked.connect(self.clear_data)
        self.button_add.clicked.connect(self.add_product)
        self.button_new.clicked.connect(self.new_product)
        self.button_find.clicked.connect(self.find_product)
        self.button_delete.clicked.connect(self.delete_product)
        self.button_edit.clicked.connect(self.edit_product)
        # self.listOfProducts.itemClicked.connect(self.Clicked)
        # self.listOfProducts.currentItemChanged.connect(self.Clicked)
        
        _translate = QtCore.QCoreApplication.translate
        window_anp.setWindowTitle(_translate("window_anp", "Dialog"))
        self.label.setText(_translate("window_anp", "Add New Product"))
        self.label_10.setText(_translate("window_anp", "%"))
        self.label_4.setText(_translate("window_anp", "HSN Code :"))
        self.label_9.setText(_translate("window_anp", "%"))
        self.label_5.setText(_translate("window_anp", "CGST :"))
        self.comboBox.setItemText(0, _translate("window_anp", "Kg"))
        self.comboBox.setItemText(1, _translate("window_anp", "gm"))
        self.comboBox.setItemText(2, _translate("window_anp", "L"))
        self.comboBox.setItemText(3, _translate("window_anp", "ml"))
        self.comboBox.setItemText(4, _translate("window_anp", "units"))
        self.label_11.setText(_translate("window_anp", "Product ID :"))
        self.label_7.setText(_translate("window_anp", "SGST : "))
        self.label_3.setText(_translate("window_anp", "UOM :"))
        self.label_2.setText(_translate("window_anp", "Product Name :"))
        self.button_add.setText(_translate("window_anp", "Add"))
        self.button_add.setShortcut(_translate("window_anp", "Ctrl+S"))
        self.button_clear.setText(_translate("window_anp", "Clear"))
        self.button_clear.setShortcut(_translate("window_anp", "Alt+C"))
        self.button_new.setText(_translate("window_anp", "New"))
        self.button_find.setText(_translate("window_anp", "Load"))
        self.button_find.setShortcut(_translate("window_anp", "Ctrl+F"))
        self.button_delete.setText(_translate("window_anp", "Delete"))
        self.button_delete.setShortcut(_translate("window_anp", "Del"))
        self.button_edit.setText(_translate("window_anp", "Edit"))
        self.button_edit.setShortcut(_translate("window_anp", "Alt+E"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window_anp = QtWidgets.QDialog()
    ui = Ui_window_anp()
    ui.setupUi(window_anp)
    window_anp.show()
    sys.exit(app.exec_())
