# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_new_vendor.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from functions_anv import *

class Ui_window_anv(object):

    def clear_data(self):
        print('clear')
        f_clear_data(self)
    def add_vendor(self):
        print('add')
        f_add_vendor(self)
    def new_vendor(self):
        print('new')
        f_new_vendor(self)


    def setupUi(self, window_anv):
        window_anv.setObjectName("window_anv")
        window_anv.resize(800, 599)
        font = QtGui.QFont()
        font.setPointSize(9)
        window_anv.setFont(font)
        self.centralwidget = QtWidgets.QWidget(window_anv)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 50, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 130, 621, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(24)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_city = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_city.sizePolicy().hasHeightForWidth())
        self.add_city.setSizePolicy(sizePolicy)
        self.add_city.setObjectName("add_city")
        self.horizontalLayout.addWidget(self.add_city)
        self.add_pincode = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_pincode.sizePolicy().hasHeightForWidth())
        self.add_pincode.setSizePolicy(sizePolicy)
        self.add_pincode.setObjectName("add_pincode")
        self.horizontalLayout.addWidget(self.add_pincode)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_district = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_district.sizePolicy().hasHeightForWidth())
        self.add_district.setSizePolicy(sizePolicy)
        self.add_district.setObjectName("add_district")
        self.horizontalLayout_2.addWidget(self.add_district)
        self.add_state = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_state.sizePolicy().hasHeightForWidth())
        self.add_state.setSizePolicy(sizePolicy)
        self.add_state.setObjectName("add_state")
        self.horizontalLayout_2.addWidget(self.add_state)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.vedor_gst_no = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vedor_gst_no.sizePolicy().hasHeightForWidth())
        self.vedor_gst_no.setSizePolicy(sizePolicy)
        self.vedor_gst_no.setObjectName("vedor_gst_no")
        self.gridLayout.addWidget(self.vedor_gst_no, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.vendor_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vendor_name.sizePolicy().hasHeightForWidth())
        self.vendor_name.setSizePolicy(sizePolicy)
        self.vendor_name.setSizeIncrement(QtCore.QSize(0, 0))
        self.vendor_name.setObjectName("vendor_name")
        self.gridLayout.addWidget(self.vendor_name, 0, 2, 1, 1)
        self.add_line1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_line1.sizePolicy().hasHeightForWidth())
        self.add_line1.setSizePolicy(sizePolicy)
        self.add_line1.setObjectName("add_line1")
        self.gridLayout.addWidget(self.add_line1, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.add_line2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_line2.sizePolicy().hasHeightForWidth())
        self.add_line2.setSizePolicy(sizePolicy)
        self.add_line2.setObjectName("add_line2")
        self.gridLayout.addWidget(self.add_line2, 2, 2, 1, 1)
        self.vendor_pan_no = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vendor_pan_no.sizePolicy().hasHeightForWidth())
        self.vendor_pan_no.setSizePolicy(sizePolicy)
        self.vendor_pan_no.setObjectName("vendor_pan_no")
        self.gridLayout.addWidget(self.vendor_pan_no, 6, 2, 1, 1)
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(430, 480, 131, 41))
        self.button_clear.setObjectName("button_clear")
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(570, 480, 131, 41))
        self.button_add.setObjectName("button_add")
        self.button_new = QtWidgets.QPushButton(self.centralwidget)
        self.button_new.setGeometry(QtCore.QRect(290, 480, 131, 41))
        self.button_new.setFlat(False)
        self.button_new.setObjectName("button_new")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(341, 509, 10, 3))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(480, 509, 10, 3))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        window_anv.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(window_anv)
        self.statusbar.setObjectName("statusbar")
        window_anv.setStatusBar(self.statusbar)

        self.button_new.setEnabled(False)

        self.retranslateUi(window_anv)
        self.button_clear.clicked.connect(self.clear_data)
        self.button_add.clicked.connect(self.add_vendor)
        self.button_new.clicked.connect(self.new_vendor)
        QtCore.QMetaObject.connectSlotsByName(window_anv)
        window_anv.setTabOrder(self.vendor_name, self.add_line1)
        window_anv.setTabOrder(self.add_line1, self.add_line2)
        window_anv.setTabOrder(self.add_line2, self.add_city)
        window_anv.setTabOrder(self.add_city, self.add_pincode)
        window_anv.setTabOrder(self.add_pincode, self.add_district)
        window_anv.setTabOrder(self.add_district, self.add_state)
        window_anv.setTabOrder(self.add_state, self.vedor_gst_no)
        window_anv.setTabOrder(self.vedor_gst_no, self.vendor_pan_no)
        window_anv.setTabOrder(self.vendor_pan_no, self.button_add)
        window_anv.setTabOrder(self.button_add, self.button_clear)

    def retranslateUi(self, window_anv):
        _translate = QtCore.QCoreApplication.translate
        window_anv.setWindowTitle(_translate("window_anv", "MainWindow"))
        self.label.setText(_translate("window_anv", "Add new vendor"))
        self.add_city.setPlaceholderText(_translate("window_anv", "City"))
        self.add_pincode.setPlaceholderText(_translate("window_anv", "Pincode"))
        self.add_district.setPlaceholderText(_translate("window_anv", "District"))
        self.add_state.setPlaceholderText(_translate("window_anv", "state"))
        self.label_4.setText(_translate("window_anv", "Vendor GST No"))
        self.label_6.setText(_translate("window_anv", "Vendor Pan No"))
        self.label_2.setText(_translate("window_anv", "Vendor Name"))
        self.add_line1.setPlaceholderText(_translate("window_anv", "Address Line 1"))
        self.label_3.setText(_translate("window_anv", "Vendor Address"))
        self.add_line2.setPlaceholderText(_translate("window_anv", "Address Line 2"))
        self.button_clear.setText(_translate("window_anv", "Clear"))
        self.button_clear.setShortcut(_translate("window_anv", "Alt+C"))
        self.button_add.setText(_translate("window_anv", "Add Vendor"))
        self.button_add.setShortcut(_translate("window_anv", "Ctrl+S"))
        self.button_new.setText(_translate("window_anv", "New"))
        self.button_new.setShortcut(_translate("window_anv", "Alt+N"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window_anv = QtWidgets.QMainWindow()
    ui = Ui_window_anv()
    ui.setupUi(window_anv)
    window_anv.show()
    sys.exit(app.exec_())
