# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_new_product.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from functions_anp import *

class Ui_window_anp(object):
    def setupUi(self, window_anp):
        window_anp.setObjectName("window_anp")
        window_anp.resize(800, 650)
        font = QtGui.QFont()
        font.setPointSize(9)
        window_anp.setFont(font)
        self.label = QtWidgets.QLabel(window_anp)
        self.label.setGeometry(QtCore.QRect(330, 80, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(window_anp)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 180, 531, 293))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(24)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 2, 1, 1)
        self.product_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_name.sizePolicy().hasHeightForWidth())
        self.product_name.setSizePolicy(sizePolicy)
        self.product_name.setSizeIncrement(QtCore.QSize(0, 0))
        self.product_name.setBaseSize(QtCore.QSize(0, 100))
        self.product_name.setObjectName("product_name")
        self.gridLayout.addWidget(self.product_name, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.cgst = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cgst.sizePolicy().hasHeightForWidth())
        self.cgst.setSizePolicy(sizePolicy)
        self.cgst.setSizeIncrement(QtCore.QSize(0, 0))
        self.cgst.setBaseSize(QtCore.QSize(0, 100))
        self.cgst.setPlaceholderText("")
        self.cgst.setClearButtonEnabled(False)
        self.cgst.setObjectName("cgst")
        self.gridLayout.addWidget(self.cgst, 5, 1, 1, 1)
        self.hsn_code = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hsn_code.sizePolicy().hasHeightForWidth())
        self.hsn_code.setSizePolicy(sizePolicy)
        self.hsn_code.setSizeIncrement(QtCore.QSize(0, 0))
        self.hsn_code.setBaseSize(QtCore.QSize(0, 100))
        self.hsn_code.setObjectName("hsn_code")
        self.gridLayout.addWidget(self.hsn_code, 4, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_5.setBaseSize(QtCore.QSize(0, 100))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 2, 1, 1)
        self.uom = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uom.sizePolicy().hasHeightForWidth())
        self.uom.setSizePolicy(sizePolicy)
        self.uom.setSizeIncrement(QtCore.QSize(0, 0))
        self.uom.setBaseSize(QtCore.QSize(0, 100))
        self.uom.setObjectName("uom")
        self.gridLayout.addWidget(self.uom, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.sgst = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sgst.sizePolicy().hasHeightForWidth())
        self.sgst.setSizePolicy(sizePolicy)
        self.sgst.setSizeIncrement(QtCore.QSize(0, 10))
        self.sgst.setBaseSize(QtCore.QSize(0, 100))
        self.sgst.setObjectName("sgst")
        self.gridLayout.addWidget(self.sgst, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.product_id = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_id.sizePolicy().hasHeightForWidth())
        self.product_id.setSizePolicy(sizePolicy)
        self.product_id.setSizeIncrement(QtCore.QSize(0, 0))
        self.product_id.setBaseSize(QtCore.QSize(0, 100))
        self.product_id.setReadOnly(True)
        self.product_id.setObjectName("product_id")
        self.gridLayout.addWidget(self.product_id, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(window_anp)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 510, 281, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(window_anp)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(200, 560, 421, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)

        self.retranslateUi(window_anp)
        QtCore.QMetaObject.connectSlotsByName(window_anp)
        window_anp.setTabOrder(self.product_name, self.uom)
        window_anp.setTabOrder(self.uom, self.comboBox)
        window_anp.setTabOrder(self.comboBox, self.hsn_code)
        window_anp.setTabOrder(self.hsn_code, self.cgst)
        window_anp.setTabOrder(self.cgst, self.sgst)
        window_anp.setTabOrder(self.sgst, self.lineEdit_5)

    def retranslateUi(self, window_anp):
        _translate = QtCore.QCoreApplication.translate
        window_anp.setWindowTitle(_translate("window_anp", "Dialog"))
        self.label.setText(_translate("window_anp", "Add New Product"))
        self.label_10.setText(_translate("window_anp", "%"))
        self.label_4.setText(_translate("window_anp", "HSN Code :"))
        self.label_5.setText(_translate("window_anp", "CGST :"))
        self.comboBox.setItemText(0, _translate("window_anp", "Kg"))
        self.comboBox.setItemText(1, _translate("window_anp", "gm"))
        self.comboBox.setItemText(2, _translate("window_anp", "L"))
        self.comboBox.setItemText(3, _translate("window_anp", "ml"))
        self.comboBox.setItemText(4, _translate("window_anp", "units"))
        self.label_9.setText(_translate("window_anp", "%"))
        self.label_8.setText(_translate("window_anp", "%"))
        self.label_3.setText(_translate("window_anp", "UOM :"))
        self.label_7.setText(_translate("window_anp", "SGST : "))
        self.label_6.setText(_translate("window_anp", "IGST :"))
        self.label_11.setText(_translate("window_anp", "Product ID :"))
        self.label_2.setText(_translate("window_anp", "Product Name :"))
        self.product_id.setText(_translate("window_anp", " 9205"))
        self.pushButton.setText(_translate("window_anp", "Add"))
        self.pushButton_2.setText(_translate("window_anp", "Clear"))
        self.pushButton_4.setText(_translate("window_anp", "Find"))
        self.pushButton_3.setText(_translate("window_anp", "Delete"))
        self.pushButton_5.setText(_translate("window_anp", "Edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window_anp = QtWidgets.QDialog()
    ui = Ui_window_anp()
    ui.setupUi(window_anp)
    window_anp.show()
    sys.exit(app.exec_())
